export default Images = [
    { url: require('../assets/1.jpg') },
    { url: require('../assets/2.jpg') },
    { url: require('../assets/3.jpg') },
    { url: require('../assets/4.jpg') },
    { url: require('../assets/5.jpg') },
    { url: require('../assets/6.jpg') },
    { url: require('../assets/7.jpg') },
    { url: require('../assets/8.jpg') },
    { url: require('../assets/2.jpg') },
    { url: require('../assets/1.jpg') },
    { url: require('../assets/2.jpg') },
    { url: require('../assets/3.jpg') },
    { url: require('../assets/4.jpg') },
    { url: require('../assets/5.jpg') },
    { url: require('../assets/6.jpg') },
    { url: require('../assets/7.jpg') },
    { url: require('../assets/8.jpg') },
    { url: require('../assets/2.jpg') },
]